language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t jonielsantos/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jonielsantos/react-test npm test

after_success:
  - docker build -t jonielsantos/multi-client ./client
  - docker build -t jonielsantos/multi-nginx ./nginx
  - docker build -t jonielsantos/multi-server ./server
  - docker build -t jonielsantos/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jonielsantos/multi-client
  - docker push jonielsantos/multi-nginx
  - docker push jonielsantos/multi-server
  - docker push jonielsantos/multi-worker